# -*- coding: utf-8 -*-
"""
/***************************************************************************
 mohid_grd_generator
                                 A QGIS plugin
 MOHID format grid generator
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-18
        copyright            : (C) 2021 by MARETEC
        email                : vasco.guita@tecnico.ulisboa.pt
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load mohid_grd_generator class from file mohid_grd_generator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mohid_grd_generator import mohid_grd_generator
    return mohid_grd_generator(iface)
